CREATE USER BD2A29 IDENTIFIED BY ACCOUNT UNLOCK ;


CREATE OR REPLACE SYNONYM Moduly FOR BD2A29.Moduly ;

CREATE OR REPLACE SYNONYM Moduly_w_obszarze FOR BD2A29.Moduly_w_obszarze ;

CREATE OR REPLACE SYNONYM Obszary_funkcjonalne FOR BD2A29.Obszary_funkcjonalne ;

CREATE OR REPLACE SYNONYM Oferty FOR BD2A29.Oferty ;

CREATE OR REPLACE SYNONYM Pracochlonnosci FOR BD2A29.Pracochlonnosci ;